edificeio/edifice-frontend-framework

packages/icons/vite.config.ts
packages/react/package.json
packages/react/vite.config.ts
pnpm-lock.yaml

fix: ts-client as devDep and react/jsx-runtime

---

packages/react/src/components/Form/TextArea.stories.tsx
packages/react/src/components/Form/TextArea.tsx
packages/react/src/components/Form/index.ts

Ajout du component "TextArea" avec la création de sa story et son export. 
Ticket: WB2-1025
- [ ] Icons

feat: #WB2-1025, create component TextArea story

---

packages/react/src/index.ts
packages/react/src/utils/functions.ts
packages/react/src/utils/index.ts

Add NOOP function in utils folder
- [ ] Icons

feat: add NOOP function in utils folder

---

packages/react/src/multimedia/MediaLibrary/MediaLibrary.tsx

fix: change modal size to md for medialibrary

---

packages/react/src/components/Toolbar/Toolbar.stories.tsx
packages/react/src/components/Toolbar/Toolbar.tsx

Proposition de refactoring de la Toolbar, afin qu'elle puisse accueillir certains types de composants.
Il s'agit de l'idée générale, les Dropdown ne sont pas gérées actuellement.
On devrait supporter Button, IconButton, Dropdown à minima.
Aussi, en l'état, l'accessibilité nécessite que chaque composant inséré dispose d'un bouton afin de pouvoir gérer le focus au clavier.
- [ ] Icons

feat: Toolbar refactoring proposal

---

packages/react/src/core/useHeader/useHeader.ts

Fix: #WB-2026, Change displayName to firstname for welcome key i18n
- [ ] Icons

fix: #WB-2026, Change display to firstname for welcome key i18n

---

packages/react/src/components/Toolbar/Toolbar.tsx

fix(toolbar): add optional overflow props

---

packages/react/src/components/Combobox/Combobox.tsx
packages/react/src/components/Combobox/ComboboxMenu.tsx
packages/react/src/components/Combobox/ComboboxTrigger.tsx
packages/react/src/components/Dropdown/DropdownContext.tsx
packages/react/src/components/Input/InputTrigger/index.ts

Ajout de petites modifications combobox pour l'adapter aux types de résultats reçus.
Ticket : #WB2-1275
https://edifice-community.atlassian.net/browse/WB2-1275
- [ ] Icons

feat: #WB2-1275, some modifs combobox

---

packages/react/src/components/Select/Select.stories.tsx

docs: update select story

---

packages/react/src/components/Dropdown/hooks/useDropdown.ts

fix(dropdown): minWidth size floating-ui

---

packages/react/src/components/Popover/Popover.tsx

add duration 0 in "useTransition" to remove transition on Popover
Ticket : WB2-1249
- [ ] Icons

fix: #WB2-1249, remove transition popover

---

packages/react/src/core/OdeClientProvider/OdeClientProvider.tsx

Ajout de la traduction sur les appcode
Ticket: WB2-1233
Lien : https://edifice-community.atlassian.net/browse/WB2-1233
- [ ] Icons

feat: #WB2-1233, add trad on appcode

---

packages/react/src/multimedia/VideoRecorder/VideoRecorder.tsx

Enable sound when playing recorded video
https://edifice-community.atlassian.net/browse/WB-2011
- [ ] Icons

fix(video): #WB-2011, enable sound when playing recorded video

---

.npmrc
packages/react/package.json
packages/react/src/tiptap/Modals/MathsModal.tsx
packages/react/src/tiptap/Modals/index.ts
packages/react/src/tiptap/index.ts

Externalize MathsModal from tiptap-playgroung to edifice-ui
- [ ] Icons

refactor: #WB-2328, add MathsModal

---

packages/react/src/components/Dropzone/DropzoneFile.tsx
packages/react/src/components/Dropzone/DropzoneImport.tsx

fix: WB-2024, add key trad

---

packages/react/package.json
packages/react/src/core/index.ts
packages/react/src/core/useWorkspaceFile/useWorkspaceFile.ts
packages/react/src/multimedia/ImageEditor/components/ImageEditor.tsx
packages/react/src/multimedia/ImageEditor/components/ImageEditorToolbar.tsx
packages/react/src/multimedia/ImageEditor/effects/blur.ts
packages/react/src/multimedia/ImageEditor/effects/crop.ts
packages/react/src/multimedia/ImageEditor/effects/misc.ts
packages/react/src/multimedia/ImageEditor/effects/resize.ts
packages/react/src/multimedia/ImageEditor/effects/rotate.ts
packages/react/src/multimedia/ImageEditor/hooks/useHistoryTool.ts
packages/react/src/multimedia/ImageEditor/hooks/useHistoryTool.tsx
packages/react/src/multimedia/ImageEditor/hooks/useImageEditor.ts
packages/react/src/multimedia/ImageEditor/hooks/useImageEditor.tsx
packages/react/src/multimedia/ImageEditor/hooks/useImageEffects.ts
packages/react/src/multimedia/ImageEditor/index.ts
packages/react/src/multimedia/ImageEditor/utils/aggregate.ts
packages/react/src/multimedia/ImageEditor/utils/debounceAggregate.ts
packages/react/src/multimedia/index.ts
packages/react/src/tiptap/ImageNodeView/index.ts
packages/react/src/tiptap/ImageNodeView/useImageSelection.ts
packages/react/src/tiptap/MediaWrapper/BubbleMenuEditImage.tsx

Ce commit embarque l'éditeur d'image et tout les effets pixi qui sont lié à la modale de l'éditeur
Il embarque également des hooks facilitant:
- la création/maj dans workspace
- la manipulation des images selectionné dans tiptap 
- [X ] Core
- [ ] Icons
- [] Hooks
- [X ] I have performed a self-review of my code
- [X ] I have commented my code, particularly in hard-to-understand areas
- [X ] My changes generate no new warnings

[EDIFICE] Feat/wb 1984 Editeur d'image

---

packages/react/src/components/Alert/Alert.stories.tsx
packages/react/src/components/Alert/Alert.tsx
packages/react/src/core/OdeClientProvider/OdeClientProvider.tsx
packages/react/src/core/useCookiesConsent/index.ts
packages/react/src/core/useCookiesConsent/useCookiesConsent.tsx
packages/react/src/core/usePreferences/index.ts
packages/react/src/core/usePreferences/usePreferences.ts

Adding Cookie Consent through the Alert Component as a "Confirm box".
Also adding "usePreferences" hook to get and save user preferences easily.
- [ ] Icons

feat: #WB2-155, add Cookie Consent feature

---

packages/react/src/multimedia/MediaLibrary/MediaLibraryContext.tsx
packages/react/src/multimedia/MediaLibrary/innertabs/Iframe.tsx
packages/react/src/multimedia/VideoEmbed/VideoEmbed.tsx

Update media library result when adding media embed
- [ ] Icons

feat: WB-2034 update media embed display

---

packages/editor/src/hooks/useMediaLibraryModal.ts
packages/react/src/core/useWorkspaceFile/useWorkspaceFile.ts
packages/react/src/multimedia/MediaLibrary/MediaLibrary.tsx
packages/react/src/multimedia/MediaLibrary/MediaLibraryContext.tsx
packages/react/src/multimedia/MediaLibrary/innertabs/Upload.tsx
pnpm-lock.yaml

Ticket WB-2385
In the MediaLibrary, when the user press Cancel => delete uploaded files.
- [ ] Icons

fix(editor): #WB-2385, delete uploaded files in BBM on cancel

---

packages/react/src/multimedia/Workspace/Workspace.tsx
pnpm-lock.yaml

Workspace tab in MediaLibrary was not supporting sort orders.
Now it does.
- [ ] Icons

fix(react): #WB-2326, support the sort order in MediaLibrary workspace

---

packages/editor/src/components/Renderer/MediaRenderer.tsx
packages/editor/src/hooks/useLinkToolbar.ts
packages/editor/src/hooks/useResizeMedia.tsx
packages/react/src/multimedia/Linker/ExternalLinker.tsx

Fix edit link with a specific text
- [ ] Icons

fix: #WB-2460 Update link text

---

packages/editor/src/components/EditorToolbar/EditorToolbar.Emoji.tsx

Remove Emoji search input and tone selector
https://edifice-community.atlassian.net/browse/WB-2486
- [ ] Icons

fix: #WB-2486, remove Emoji search input and tone selector

---

packages/react/src/core/index.ts
packages/react/src/core/useHttpErrorToast/index.ts
packages/react/src/core/useHttpErrorToast/useHttpErrorToast.ts
packages/react/src/core/useUploadFiles/useUploadFiles.ts
packages/react/src/multimedia/MediaLibrary/MediaLibrary.tsx
pnpm-lock.yaml

Display a toast with details read from the backend response, when uploading a media fails.
Uses `ts-client notify.events()` API
- [ ] Icons

[EDIFICE] Display a toast on error in MediaLibrary.

---

packages/editor/src/components/BubbleMenuEditImage/BubbleMenuEditImage.tsx
packages/editor/src/components/EditorToolbar/EditorToolbar.DropdownMenu.tsx
packages/editor/src/components/EditorToolbar/EditorToolbar.Emoji.tsx
packages/editor/src/components/EditorToolbar/EditorToolbar.HighlightColor.tsx
packages/editor/src/components/EditorToolbar/EditorToolbar.PlusMenu.tsx
packages/editor/src/components/EditorToolbar/EditorToolbar.TextColor.tsx
packages/editor/src/components/EditorToolbar/EditorToolbar.TextSize.tsx
packages/editor/src/components/EditorToolbar/EditorToolbar.Typography.tsx
packages/editor/src/components/EditorToolbar/EditorToolbar.tsx
packages/editor/src/components/Toolbar/LinkToolbar.tsx
packages/editor/src/components/Toolbar/TableToolbar.AddMenu.tsx
packages/editor/src/components/Toolbar/TableToolbar.CellColor.tsx
packages/editor/src/components/Toolbar/TableToolbar.DelMenu.tsx
packages/editor/src/components/Toolbar/TableToolbar.tsx
packages/react/src/components/Dropdown/DropdownTrigger.tsx
packages/react/src/components/Toolbar/Toolbar.tsx
packages/react/src/components/Tooltip/Tooltip.tsx
packages/react/src/components/UploadCard/UploadCard.tsx
packages/react/src/multimedia/AudioRecorder/AudioRecorder.tsx
packages/react/src/multimedia/AudioRecorder/useAudioRecorder.tsx
packages/react/src/multimedia/VideoRecorder/VideoRecorder.tsx

Add Tooltip component where needed : 
- Toolbars
- Update Toolbar component to handle message + position for tooltip
- [ ] Icons

feat: #WB-2448, add tooltip i18n

---

packages/editor/src/components/BubbleMenuEditImage/BubbleMenuEditImage.tsx
packages/editor/src/components/Editor/Editor.tsx

Modification du bubblemenu pour que la toolbar soit flotante lors du scroll
- [ ] Icons

fix: #WB-1985, fix toolbar position

---

packages/editor/src/hooks/useMediaLibraryModal.ts

Issue when adding multiple multimédia content. [#WB-2453](https://edifice-community.atlassian.net/browse/WB-2453) 
The fix will add the contents and select only the last one.
- [ ] Icons

fix: #WB-2453 Add multiple multimedia content

---

packages/editor/src/components/BubbleMenuEditImage/BubbleMenuEditImage.tsx

Refacto de bubblement avec le composant toolbar
Lien Ticket : https://edifice-community.atlassian.net/browse/WB-2497
- [ ] Icons

fix: #WB-2497, refacto bubbleMenu with toolbar component

---

packages/react/src/multimedia/ImageEditor/components/ImageEditorToolbar.tsx

J'ai retiré ta toolbar custom pour utiliser le composant `Toolbar` qui est configurable avec un tableau d'objets. J'ai retesté sur le playground, tout a l'air OK, mais n'hésite pas à faire une repasse 👍🏼 
- [ ] Icons

fix(toolbar): use correct toolbar component for image editor

---

packages/react/src/core/useHttpErrorToast/useHttpErrorToast.ts

Adaptation to refactor done in https://github.com/opendigitaleducation/edifice-ts-client/pull/23
- [ ] Icons

fix: use the new ts-client events() system

---

packages/editor/src/components/EditorToolbar/EditorToolbar.tsx
packages/editor/src/hooks/useLinkToolbar.ts
packages/editor/src/hooks/useMediaLibraryModal.ts
packages/react/src/multimedia/ImageEditor/components/ImageEditorToolbar.tsx
packages/react/src/multimedia/Linker/ExternalLinker.stories.tsx
packages/react/src/multimedia/Linker/ExternalLinker.tsx
packages/react/src/multimedia/MediaLibrary/MediaLibrary.tsx
packages/react/src/multimedia/MediaLibrary/innertabs/ExternalLink.tsx
packages/react/src/utils/StringUtils.ts

Fix behavior when text is selected and we try to add/edit a link.
- [ ] Icons

fix: #WB-2460 Update behavior when text selected and add/edit link

---

packages/react/src/common/ShareModal/ShareBookmarkLine.tsx

Show user profile in Share modal table.
Ticket: https://edifice-community.atlassian.net/browse/WB2-1383
- [ ] Icons

fix: #WB2-1383, show user profile in Share modal table

---

packages/editor/src/components/Editor/Editor.tsx
packages/editor/src/components/EditorToolbar/EditorToolbar.tsx

Ajout d'un _variant_ `ghost` à l'éditeur, afin de permettre un rendu sans bordures.
- [ ] Icons

feat(editor): #WB-2382, ghost variant for fullscreen editor

---

packages/editor/src/hooks/index.ts
packages/editor/src/hooks/useCommentEditor.ts
packages/editor/src/hooks/useMediaLibraryModal.ts
packages/editor/src/hooks/useTipTapEditor.ts
packages/editor/src/index.ts
packages/react/src/core/useDate/index.ts
packages/react/src/core/useDate/useDate.ts

Comments can contain hyperlinks, so a dedicated tiptap editor with a few plugins was required.
* new hook : `useCommentEditor`
where characters count is maintained, and setting maxlength is possible.
* `EditorContent, type Content, useEditor` are exported to allow applications to integrate their own custom editor.
* Updated some inaccurate comments in source code.
- [ ] Icons

feat: #WB-2362, edit a comment

---

packages/react/src/utils/thumbnail.ts

feat: Add thumbnail utils

---

packages/react/src/multimedia/VideoRecorder/VideoRecorder.tsx

Update responsible display.
- [ ] Icons

fix(react): #WB-2541 update record on responsive

---

packages/editor/package.json
packages/editor/src/components/Editor/Editor.tsx
packages/editor/src/hooks/useTipTapEditor.ts

Add Tiptap Placeholder extension
Related ticket: https://edifice-community.atlassian.net/browse/WB2-1590
- [ ] Icons

feat: #WB2-1590, add Tiptap Placeholder extension

---

packages/react/src/multimedia/ImageEditor/components/ImageEditor.tsx
packages/react/src/multimedia/ImageEditor/effects/blur.ts
packages/react/src/multimedia/ImageEditor/effects/crop.ts
packages/react/src/multimedia/ImageEditor/effects/misc.ts
packages/react/src/multimedia/ImageEditor/hooks/useHistoryTool.ts
packages/react/src/multimedia/ImageEditor/hooks/useImageEditor.ts

Fix update a big file and loose image quality.
Force max-width and max-height.
[Related PR in edifice-bootstrap](https://github.com/edificeio/edifice-bootstrap/pull/59)
- [ ] Icons

fix: #WB-2799 image update quality

---

packages/react/src/multimedia/AudioRecorder/useAudioRecorder.tsx

Clear buffer by sending "cancel"
- [ ] Icons

fix: #WB-2910 reset websocket buffer

---

lerna.json
packages/editor/package.json
packages/editor/src/components/Renderer/AudioRenderer.tsx
packages/editor/src/hooks/useMathsStyles.ts
packages/icons/package.json
packages/react/package.json
packages/react/src/multimedia/Workspace/Workspace.tsx
pnpm-lock.yaml

chore: pre-release

---

packages/react/ui/src/common/ResourceModal/ResourceModal.tsx
packages/react/ui/src/components/TextArea/TextArea.tsx

Add Resource Modal title and description maxLength
- [ ] Icons

feat: #WB2-1496, add resource title/description maxLength

---

packages/react/ui/src/multimedia/AudioRecorder/AudioRecorder.tsx
packages/react/ui/src/multimedia/AudioRecorder/AudioRecorderTimer.tsx
packages/react/ui/src/multimedia/AudioRecorder/useAudioRecorder.tsx

Performance issue when record is too long so we add a maximum duration same as the video record.
- [ ] Icons

fix(ui): #WB-2912 add maximum duration to audio record

---

packages/react/ui/src/multimedia/Linker/InternalLinker.tsx

[Ticket WB-2925](https://edifice-community.atlassian.net/browse/WB-2925)
BBM : filter on lowercase text
- [ ] Icons

fix(multimedia): #WB-2925, filtering of resources from workspace, in lowercase

---

packages/client/src/ts/workspace/Service.ts

[Ticket WB-2855](https://edifice-community.atlassian.net/browse/WB-2855)
Video files from Workspace may have no thumbnail image.
In this case, the video file itself was returned as the thumbnail, and Safari was playing it, causing unwanted traffic over the network.
=> The workspace function `getThumbnailUrl()` has been corrected to avoid returning a video file instead of a still image.
- [ ] Icons

fix(client): do not use video files as thumbnails

---

packages/react/ui/src/core/useDate/useDate.ts

Update format date to take care of the localized format
- [ ] Icons

fix(ui): #WB-2690 format date

---

packages/react/ui/src/multimedia/AudioRecorder/AudioRecorder.tsx
packages/react/ui/src/multimedia/AudioRecorder/useAudioRecorder.tsx
packages/react/ui/src/multimedia/MediaLibrary/innertabs/Audio.tsx

Remove the pre-processor + the websocket for audio captation. 
Replace them by a mediaRecorder + audioEncoder (same used before to cover to MP3) 
And save the audio file via workspace API
- [ ] Icons

fix: #WB-2912 audio performance without websocket

---

packages/react/ui/src/core/useWorkspaceSearch/useWorkspaceSearch.ts
packages/react/ui/src/multimedia/Workspace/Workspace.tsx
packages/react/ui/src/utils/findTreeNode.ts
packages/react/ui/src/utils/index.ts

> [Ticket WB-3056](https://edifice-community.atlassian.net/browse/WB-3056)
Ce commit corrige et factorise 2 problèmes similaires de parcours de l'arborescence de TreeNode.
- [ ] Icons

fix(multimedia): tree node search algorithm

---

packages/react/ui/src/components/UploadCard/UploadCard.tsx
packages/react/ui/src/multimedia/UploadFiles/UploadFiles.tsx

fix(ui): #WB-3054, use blob as a thumbnail to avoid unnecessary requests

---

packages/react/ui/src/core/useUploadFiles/useUploadFiles.ts
packages/react/ui/src/hooks/useImageResizer/index.ts
packages/react/ui/src/hooks/useImageResizer/useImageResizer.mdx
packages/react/ui/src/hooks/useImageResizer/useImageResizer.stories.tsx
packages/react/ui/src/hooks/useImageResizer/useImageResizer.ts

Add new hook useImageResizer to resize and compress a image file. 
Used in the useUploadFiles hook to apply a width/height max size and a compression.
- [ ] Icons

feature(ui): #WB-2036 image resizer

---

packages/react/ui/src/core/useWorkspaceFile/useWorkspaceFile.ts
packages/react/ui/src/multimedia/MediaLibrary/MediaLibrary.tsx
packages/react/ui/src/multimedia/MediaLibrary/MediaLibraryContext.tsx
packages/react/ui/src/multimedia/MediaLibrary/innertabs/Upload.tsx

> [Ticket WB-3082](https://edifice-community.atlassian.net/browse/WB-3082)
- [ ] Icons

fix: #WB-3082, do not try to delete uploaded files removed earlier

---

packages/react/ui/src/components/Dropzone/Dropzone.tsx
packages/react/ui/src/hooks/useDropzone/useDropzone.ts
packages/react/ui/src/multimedia/MediaLibrary/innertabs/Upload.tsx
packages/react/ui/src/multimedia/UploadFiles/UploadFiles.tsx

> [Ticket WB-3075](https://edifice-community.atlassian.net/browse/WB-3075)
- [ ] Icons
- [X My code follows the style guidelines of this project

fix: #WB-3075, do not import files of wrong type

---

packages/react/ui/src/hooks/useImageResizer/useImageResizer.ts
packages/react/ui/src/multimedia/MediaLibrary/innertabs/Upload.tsx

Force compression into JPEG file (compression with other format doesn't work with canvas.
- [ ] Icons

feature(ui): #WB-2036 force jpeg to enable compression

---

packages/client/src/ts/data/Service.ts
packages/client/src/ts/data/interface.ts

Add ACCESS_LIBRARY_FROM_EXPLORER event to Data Service.
https://edifice-community.atlassian.net/browse/WB2-1555
- [ ] Icons

feat: #WB2-1778, add ACCESS_LIBRARY_FROM_EXPLORER event to Data Service

---

packages/react/ui/src/core/OdeClientProvider/OdeClientProvider.tsx

Disable translate on the entire page to fix issues provoced by google translate. 
- [ ] Icons

fix(ui): #WB-3137 disable translate on html

---

packages/client/src/ts/audience/ReactionsService.ts
packages/client/src/ts/audience/interface.ts
packages/client/src/ts/session/Service.ts
packages/react/ui/src/components/Audience/ReactionModal.Card.tsx
packages/react/ui/src/components/Audience/ReactionModal.tsx
packages/react/ui/src/components/Audience/ReactionSummary.tsx
packages/react/ui/src/components/Audience/ViewsByProfileCard.tsx
packages/react/ui/src/components/Audience/ViewsCounter.tsx
packages/react/ui/src/components/Audience/ViewsModal.tsx
packages/react/ui/src/components/Audience/hooks/useReactions.ts
packages/react/ui/src/components/Audience/index.ts
packages/react/ui/src/components/Audience/stories/ReactionModal.stories.tsx
packages/react/ui/src/core/index.ts
packages/react/ui/src/core/useAvatar/index.ts
packages/react/ui/src/core/useAvatar/useAvatar.tsx
packages/react/ui/src/utils/StringUtils.ts

> [Ticket WB-3002](https://edifice-community.atlassian.net/browse/WB-3002)
Il s'agit de la modale détaillant les réactions faites par des User sur une resource.
- [ ] Icons

feat(ui): #WB-3002, reactions details modal

---

packages/bootstrap/scss/components/views/_views-detail.scss
packages/react/ui/src/components/Audience/ReactionSummary.tsx
packages/react/ui/src/components/Audience/ViewsCounter.tsx
packages/react/ui/src/components/Audience/ViewsModal.tsx
public/assets/themes/edifice-bootstrap/index.css

feat(ui): #WB-2998 audience prevent defaut on click

---

packages/react/ui/src/components/Audience/ReactionChoice.tsx
packages/react/ui/src/components/Dropdown/Dropdown.tsx
packages/react/ui/src/components/Dropdown/DropdownItem.tsx
packages/react/ui/src/components/Dropdown/DropdownTrigger.tsx
packages/react/ui/src/hooks/useDropdown/useDropdown.ts

Stop event propagation on dropdown item clique
- [ ] Icons

fix: #WB-3003 stop propagation dropdown item click

---

packages/react/ui/src/components/Audience/ReactionChoice.tsx
packages/react/ui/src/components/Audience/ReactionModal.tsx
packages/react/ui/src/hooks/useDropdown/useDropdown.ts

fix: #WB-3158 audience fine tuning

---

packages/bootstrap/scss/components/_card.scss

Update highlight of the button when card is selected (only on header button)
- [ ] Icons

fix: #WB-3163 card selected highlight button

---

packages/client/src/ts/embedder/Service.ts

fix(client): #WB-2866 catch youtube id with embed url

---

packages/bootstrap/scss/components/_dropdown.scss
packages/react/ui/src/components/Audience/ReactionChoice.tsx

Remove hover on dropdown for ReactionChoice
- [ ] Icons

fix(ui): #WB-3205 remove hover reaction choice

---

lerna.json
packages/bootstrap/package.json
packages/client/package.json
packages/react/editor/package.json
packages/react/icons/package.json
packages/react/ui/package.json
packages/react/ui/src/core/useHeader/useHeader.ts
packages/tiptap/extensions/extension-abbr/package.json
packages/tiptap/extensions/extension-alert/package.json
packages/tiptap/extensions/extension-attachment/package.json
packages/tiptap/extensions/extension-audio/package.json
packages/tiptap/extensions/extension-font-size/package.json
packages/tiptap/extensions/extension-heading/package.json
packages/tiptap/extensions/extension-highlight/package.json
packages/tiptap/extensions/extension-hyperlink/package.json
packages/tiptap/extensions/extension-iframe/package.json
packages/tiptap/extensions/extension-image/package.json
packages/tiptap/extensions/extension-line-height/package.json
packages/tiptap/extensions/extension-linker/package.json
packages/tiptap/extensions/extension-mathjax/package.json
packages/tiptap/extensions/extension-paragraph/package.json
packages/tiptap/extensions/extension-speechrecognition/package.json
packages/tiptap/extensions/extension-speechsynthesis/package.json
packages/tiptap/extensions/extension-table-cell/package.json
packages/tiptap/extensions/extension-video/package.json
packages/tiptap/extensions/transform/package.json

release: 1.5.16

---

packages/bootstrap/scss/components/_treeview.scss
packages/react/ui/src/components/TreeView/TreeNode.tsx
packages/react/ui/src/components/TreeView/TreeView.tsx

Ajout du bouton permettant de créer une page enfant a partir du treeview + ajout du css correspondant au bouton
- [ ] Icons

feat: #WB2-1516, add button to create children page

---

packages/react/editor/src/components/Renderer/AttachmentRenderer.tsx
packages/react/editor/src/components/Renderer/AudioRenderer.tsx
packages/react/editor/src/components/Renderer/LinkerRenderer.tsx
packages/react/editor/src/components/Renderer/MediaRenderer.tsx
packages/react/editor/src/components/Renderer/index.ts
packages/react/ui/src/components/AppIcon/AppIcon.tsx
packages/react/ui/src/components/AppIcon/index.ts
packages/react/ui/src/components/Breadcrumb/Breadcrumb.tsx
packages/react/ui/src/components/Breadcrumb/index.ts
packages/react/ui/src/components/ImagePicker/ImagePicker.tsx
packages/react/ui/src/components/ImagePicker/index.ts
packages/react/ui/src/components/UploadCard/UploadCard.tsx
packages/react/ui/src/components/UploadCard/index.ts
packages/react/ui/src/core/useHttpErrorToast/index.ts
packages/react/ui/src/core/useHttpErrorToast/useHttpErrorToast.ts
packages/react/ui/src/portal/Header/WidgetApps.tsx
packages/react/ui/src/widgets/BookmarkedApps/BookmarkedApps.tsx

fix(react): #WB2-1843, remove re-exports issues

---

packages/react/ui/src/multimedia/VideoRecorder/VideoRecorder.tsx

[Ticket WB-3012](https://edifice-community.atlassian.net/browse/WB-3012)
- [ ] Icons

fix(multimedia): #WB-3012, stop any playing video before save

---

packages/react/ui/src/common/ShareModal/apps/ShareBlog.tsx

Add useEffect to re-render when publish-type changes
- [ ] Icons

fix(share): #WB2-1889, add useEffect to update blog publish-type

---

packages/react/editor/src/components/Renderer/MediaRenderer.tsx

fix(editor): #WB-3226 remove editor image attribute textAlign

---

packages/react/editor/src/components/Renderer/MediaRenderer.tsx

fix(editeur): #WB-3227 cast controls attribut to boolean

---

packages/react/editor/package.json
packages/react/editor/src/components/Editor/Editor.tsx
packages/react/editor/src/components/Editor/FileHandlerConfig.tsx
packages/react/editor/src/components/Editor/index.ts
packages/react/editor/src/hooks/useTipTapEditor.ts
packages/react/ui/src/core/index.ts
packages/react/ui/src/hooks/index.ts
pnpm-lock.yaml

Add file handler extension on tiptap to allowed user to copy paste or drop image files
- [ ] Icons

fix(editor): #WB-3308 enable copy paste images files

---

packages/react/editor/src/components/Renderer/MediaRenderer.tsx
packages/react/ui/src/multimedia/ImageEditor/components/ImageEditor.tsx

Add legend under image.
- [ ] Icons

fix: #WB-2538 add legend under images

---

packages/client/src/ts/resources/SnipletsService.ts
packages/client/src/ts/resources/behaviours/MagnetoBehaviour.ts
packages/react/ui/src/components/AppIcon/AppIcon.tsx
packages/react/ui/src/multimedia/Linker/InternalLinker.tsx

https://edifice-community.atlassian.net/browse/EN-15
- [ ] Icons

fix: #EN-15, fixes to show magneto app in internal linker

---

packages/tiptap/extensions/extension-image/src/CustomImage.ts

fix(tiptap): #WB-2538 regression on past text

---

Jenkinsfile
docker-compose.yml
edifice.config.js
packages/cli/src/publish/index.js

chore: #EN-47, add jenkinsfile, docker-compose to build and publish packages

---

packages/react/ui/src/core/useUploadFiles/useUploadFiles.ts

Add legend when import images
- [ ] Icons
- [] Chore (PATCH)

fix: #WB-3511 add legend when import image

---

apps/docs/src/i18n.ts
apps/docs/src/index.ts
apps/docs/src/lib/docs.tsx
apps/docs/src/lib/stories/icons/Icons-apps.mdx
edifice.config.js
packages/react/editor/package.json
packages/react/ui/src/components/Avatar/Avatar.stories.tsx
packages/react/ui/src/components/EmptyScreen/EmptyScreen.stories.tsx
packages/react/ui/src/core/usePaths/usePaths.ts
packages/react/ui/src/hooks/useImage/useImage.stories.tsx
packages/react/ui/src/multimedia/Workspace/Workspace.tsx
pnpm-lock.yaml

fix: #EN-57, add BASE_URL to usePaths hook to fix storybook and apps paths urls

---

package.json
packages/client/package.json
packages/client/vite.config.ts
packages/react/editor/package.json
packages/react/editor/vite.config.ts
packages/react/icons/package.json
packages/react/icons/vite.config.ts
packages/react/ui/package.json
packages/react/ui/vite.config.ts
packages/tiptap/extensions/extension-image/package.json
pnpm-workspace.yaml

chore(build): #EN-41, optimize tree-shaking with Vite configuration

---

packages/react/src/components/Modal/Modal.tsx
packages/react/src/hooks/useTrapFocus/useTrapFocus.ts
packages/react/src/modules/comments/components/Comment.tsx
packages/react/src/modules/comments/components/DeleteModal.tsx
packages/react/src/modules/comments/context/Context.ts
packages/react/src/modules/comments/hooks/useComments.ts
packages/react/src/modules/comments/provider/CommentProvider.tsx
packages/react/src/modules/comments/types.ts

https://edifice-community.atlassian.net/browse/WB2-2213
- [ ] Icons

feat(comments): WB2-2213, add DeleteModal and userRights to allow manager to delete comment

---

packages/client/src/ts/globals.ts
packages/client/src/ts/resources/interface.ts
packages/client/src/ts/resources/services/TimelineGeneratorResourceService.ts
packages/client/src/ts/services/index.ts
packages/react/src/components/Attachment/Attachment.tsx

Adding TimelineGeneratorService for Timeline generator app Explorer portage.
This PR is related to this one: https://github.com/OPEN-ENT-NG/timeline-generator/pull/19
- [ ] Icons

feat: #WB2-1928, adding TimelineGenerator Service for EUR

---

packages/react/src/components/SearchBar/Search.stories.tsx
packages/react/src/components/SearchBar/SearchBar.tsx

Add InputProps to `SearchBar` element to be able to set `value` or `defaultValue`

feat(react): #WB-3759 add default value to searchbar

---

packages/react/src/hooks/useCheckable/useCheckable.ts

`allItemsSelected` must be set as false when there are no items

feat(react): #WB-3760 allItemsSelected when no items

---

apps/docs/i18n.ts
packages/react/src/modules/multimedia/Workspace/Workspace.stories.tsx

docs(Workspace): ENABLING-193, add stories

---

packages/react/src/components/Dropdown/stories/Dropdown.Item.stories.tsx
packages/react/src/components/Dropdown/stories/Dropdown.Trigger.stories.tsx
packages/react/src/components/Dropdown/stories/Dropdown.stories.tsx

docs(Dropdown): ENABLING-195, add source code in Dropdown Story

---

apps/docs/.storybook/preview.tsx
packages/react/src/modules/comments/CommentProvider.mdx
packages/react/src/modules/comments/CommentProvider.stories.tsx
packages/react/src/modules/comments/components/Comment.tsx

docs: ENABLING-201, fix mock to update comment provider doc

---

package.json
packages/client/package.json
packages/extensions/package.json
packages/utilities/package.json

chore: ENABLING-203, clean package.json root

---

packages/client/src/ts/globals.ts
packages/client/src/ts/resources/interface.ts
packages/client/src/ts/resources/services/CollaborativeEditorResourceService.ts
packages/client/src/ts/services/index.ts

Add CollaborativeEditor Resource Service for EUR.
- [ ] Icons

feat: #WB2-1926, add CollaborativeEditor Resource Service for EUR

---

packages/extensions/package.json
packages/extensions/src/conversation-history/conversation-history.ts
packages/extensions/src/conversation-history/index.ts
packages/extensions/src/index.ts

Task [#WB-3812](https://edifice-community.atlassian.net/browse/WB-3812)

feat(extension): #WB-3812 new extension conversation history

---

packages/react/src/modules/modals/ConfirmModal/ConfirmModal.stories.tsx
packages/react/src/modules/modals/ConfirmModal/ConfirmModal.tsx
packages/react/src/modules/modals/ConfirmModal/index.ts
packages/react/src/modules/modals/index.ts

feat(react): WB-3457 Add Confirm Modal on modules of frontend framework

---

apps/docs/src/i18n.ts
packages/bootstrap/src/components/_comments.scss
packages/react/src/modules/comments/CommentProvider.mdx
packages/react/src/modules/comments/CommentProvider.stories.tsx
packages/react/src/modules/comments/components/Comment.tsx
packages/react/src/modules/comments/components/CommentForm.tsx
packages/react/src/modules/comments/components/CommentList.tsx
packages/react/src/modules/comments/components/CommentReplies.tsx
packages/react/src/modules/comments/constants.ts
packages/react/src/modules/comments/context/Context.ts
packages/react/src/modules/comments/hooks/useCommentReplies.ts
packages/react/src/modules/comments/hooks/useComments.ts
packages/react/src/modules/comments/provider/CommentProvider.tsx
packages/react/src/modules/comments/types.ts

Adding Comments Replies component: https://edifice-community.atlassian.net/browse/WB-2277
It's not 100% finished (TODO: show replies even if the comment is deleted) but I wanted to show it to Alicia to have some UX/UI feedback, as the ticket has been under construction since some days now (due to urgent bugfixes and deployments on other topics...)
Features:
- You can reply to a comment by clicking on the Reply button.
- You can limit the number of replies displayed by setting the `maxReplies` option.
- You can also load more replies by clicking on the Load More button. The number of replies loaded is determined by the `additionalReplies` option.
- Only one level of replies is supported.
- [ ] Icons
- …

feat(comments): #WB2-1941, add Comments Replies component

---

packages/react/src/components/Layout/hooks/useHelp.tsx

fix(help): #MED-355 add active section state to manage visibility of help content

---

packages/client/src/ts/workspace/Service.ts
packages/config/src/msw/mocks/workspace.ts
packages/react/src/hooks/index.ts
packages/react/src/hooks/useWorkspaceFolders/index.ts
packages/react/src/hooks/useWorkspaceFolders/useWorkspaceFolders.ts
packages/react/src/modules/modals/AddAttachmentToWorkspaceModal/AddAttachmentToWorkspaceModal.stories.tsx
packages/react/src/modules/modals/AddAttachmentToWorkspaceModal/AddAttachmentToWorkspaceModal.tsx
packages/react/src/modules/modals/AddAttachmentToWorkspaceModal/components/WorkspaceFoldersTree.tsx
packages/react/src/modules/modals/AddAttachmentToWorkspaceModal/index.ts
packages/react/src/modules/modals/ConfirmModal/ConfirmModal.tsx
packages/react/src/modules/modals/index.ts

add AddAttachmentToWorkspaceModal
add listFolder Service
add useWorkspaceFolders hook
- [ ] Icons

feat(addAttachmentToWorkspaceModal):#WB-3447 add module

---

packages/react/src/hooks/useWorkspaceFolders/useWorkspaceFolders.ts
packages/react/src/modules/multimedia/WorkspaceFolders/WorkspaceFolders.tsx

Filtrer les dossiers avec une bar de recherche
-useWorkspaceFolders.js
-WorkspaceFolders.tsx
- [ ] Icons

feat(react):#WB-3970 WorkspaceFolders - search folder in list

---

packages/react/src/components/Flex/Flex.stories.tsx
packages/react/src/components/Flex/Flex.tsx

`<Flex>` composant : 
```
<Flex
align="start"
className="custom-class-name"
direction="row-reverse"
gap="4"
justify="end"
wrap
>
<div className="p-2 bg-primary text-white">
Box 1
</div>
<div className="p-2 bg-secondary text-white">
Box 2
</div>
</Flex>
```
- [ ] Icons

feat(react):#WB2-2688 component Flex

---

packages/bootstrap/src/components/_modal.scss
packages/react/src/modules/modals/ConfirmModal/ConfirmModal.tsx

fix margin on mobile
- [ ] Icons

fix(ConfirmModal):WB-4005 fix margin on mobile

---

packages/client/src/ts/workspace/interface.ts
packages/config/src/msw/mocks/workspace/data/folders.ts
packages/config/src/msw/mocks/workspace/data/sharedFolders.ts
packages/config/src/msw/mocks/workspace/workspace.ts
packages/react/src/hooks/useWorkspaceFolders/useWorkspaceFolders.ts
packages/react/src/modules/multimedia/WorkspaceFolders/WorkspaceFolders.tsx
packages/react/src/modules/multimedia/WorkspaceFolders/components/NewFolderForm.tsx

- select created folder 
- optimize queries (not invalidate get query by updating the cache)
- [ ] Icons

feat(WorkspaceFolders):WB-3971 select created folder + optimize queries

---

packages/bootstrap/src/components/_table.scss
packages/react/src/components/Table/Table.stories.tsx
packages/react/src/components/Table/components/Table.tsx

Ajout d'une props pour intégrer un scroll dans le composant <Table/>
- [ ] Icons

feat: #WB2-2565, add scroll in table component

---

packages/react/src/hooks/useHttpErrorToast/useHttpErrorToast.ts

useHttpErrorMessage est corrigé comme suit : 
* il essaie de trouver une traduction correcte de l'erreur HTTP, avant d'afficher le texte technique.
* si aucun texte n'est trouvé, il n'affiche plus de toast vide.
- [ ] Icons

fix(react): #WB-3925, useHttpErrorMessage should not display empty toasts

---

packages/bootstrap/src/components/tiptap/_conversation-history.scss

fix(conversation): #WB-3438 add conversation history

---

packages/bootstrap/src/components/_tabs.scss
packages/react/src/components/Tabs/Tabs.stories.tsx
packages/react/src/components/Tabs/components/TabsItem.tsx

Modification du composant <Tab> pour pouvoir ajouter un badge de notification dans une ou plusieurs tabs.
- [ ] Icons

feat: #PEDAGO-2543, add new props badge in tabs

---

packages/config/src/msw/mocks/userbook.ts
packages/react/src/modules/modals/OnboardingModal/OnboardingModal.stories.tsx
packages/react/src/modules/modals/OnboardingModal/OnboardingModal.tsx

Onboarding modal :
-add to storybook
-center text
-add a title per slide
- [ ] Icons

fix(react)-OnboardingModal fixes + updates

---

packages/react/src/components/List/List.tsx

add sticky toolbar option to list
- [ ] Icons

feat(react)-COCO-4122-sticky-toolbar-list

---

packages/bootstrap/src/components/_combobox.scss
packages/react/src/components/Combobox/Combobox.stories.tsx
packages/react/src/components/Combobox/Combobox.tsx
packages/react/src/components/Combobox/ComboboxTrigger.tsx
packages/react/src/components/Dropdown/Dropdown.tsx
packages/react/src/hooks/useDropdown/useDropdown.ts

Combobox add feat to be able to focus the input inside the trigger for custom renderList 
Fix remove focus when mouseEnter in the dropdown item
- [ ] Icons

fix(combobox): #COCO-4024 combobox be able to focus input

---

packages/client/src/ts/transport/Service.ts

Add Http Patch method to the Http Service.
- [ ] Icons

feat: add Http Patch method to Http Service

---

packages/bootstrap/src/base/_utilities.scss
packages/react/src/hooks/useLibraryUrl/useLibraryUrl.ts

chore: ff lirary url debug

---

packages/bootstrap/src/components/_buttons.scss
packages/bootstrap/src/components/_form-control.scss
packages/react/src/components/SearchBar/SearchBar.tsx

SearchBar
- ajout de l'etat disable pour le bouton de recherche
- customise la croix pour effacer le texte
- [ ] Icons

fix(conversation): #COCO-4215 add disabled state to searchbar button

---

packages/react/src/hooks/useDropdown/useDropdown.ts

[COCO-4200](https://edifice-community.atlassian.net/browse/COCO-4200) There is an issue with the navigation by keyboard for the dropdown some times you have to press multiples times the down arrow key to get down on the list. 
- [ ] Icons
[COCO-4200]: https://edifice-community.atlassian.net/browse/COCO-4200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(react): #COCO-4200 keyboard navigation dropdown

---

packages/react/src/components/Tabs/Tabs.stories.tsx
packages/react/src/components/Tabs/components/Tabs.tsx
packages/react/src/components/Tabs/components/TabsList.tsx

Add feature on tabs bar to have a tab bar.
- [ ] Icons

feat: #PEDAGO-2566 sticky tabs bar
