packages/react/src/components/Toolbar/Toolbar.tsx

La Toolbar autorise l'affichage de ses boutons en surbrillance, afin de signaler que l'action sous-jacente est activée.
Mais lorsque le bouton est un trigger de dropdown, cela ne fonctionnait pas.
Ce fix corrige simplement le problème.
- [ ] Icons

feat(toolbar): #WB-1954, allow dropdown triggers to be active

---

packages/react/src/components/ColorPicker/ColorPalette.tsx
packages/react/src/components/ColorPicker/ColorPicker.stories.tsx
packages/react/src/components/ColorPicker/ColorPicker.tsx

Ce fix corrige les problèmes relevés dans le ticket WB-1954 : 
* possibilité de mettre le titre d'une palette en gras ou non,
* possibilité d'ajouter, à une palette, un tooltip d'information,
* possibilité de pouvoir gérer la couleur sélectionnée en dehors du composant.
- [ ] Icons

Fix(color-picker): WB-1954, unwanted bold font, missing tooltip info, default background and text colors

---

packages/icons/assets/no-colors.svg
packages/icons/src/NoColors.tsx
packages/icons/src/index.ts
packages/react/src/components/ColorPicker/ColorPalette.tsx
packages/react/src/components/ColorPicker/ColorPicker.stories.tsx
packages/react/src/components/ColorPicker/ColorPicker.tsx

Ajout d'une option pour les palettes de couleurs, affichées par le ColorPicker, qui contient la description d'une couleur de "reset" pouvant être transparent. Par défaut, le bouton affiché est _d'argent à la barre de gueules_.

feat(color-picker): #WB-2175, color reset option

---

packages/react/src/components/LoadingScreen/LoadingScreen.stories.tsx
packages/react/src/components/LoadingScreen/LoadingScreen.tsx
packages/react/src/components/Toolbar/Toolbar.tsx
packages/react/src/multimedia/VideoRecorder/VideoRecorder.tsx

Adding LoadingScreen to video saving action.
Adding caption prop to LoadingScreen component to show a caption below the loading icon.
- [ ] Icons

feat: add LoadingScreen to VideoRecorder saving

---

packages/react/src/components/Toolbar/Toolbar.tsx
packages/react/src/multimedia/VideoRecorder/VideoRecorder.tsx

Set record button to danger button.
Update Toolbar component to check if toolbar item has a color prop to use it for toolbar button color, otherwise use "tertiary" as default.
- [ ] Icons

[VideoRecorder] Fix #WB-1988: set video record button to danger button

---

packages/react/src/components/Dropdown/Dropdown.tsx
packages/react/src/components/Dropdown/hooks/useDropdown.ts
packages/react/src/components/Toolbar/Toolbar.stories.tsx
packages/react/src/components/Toolbar/Toolbar.tsx

Handle the a11y navigation with keyboard arrows between simple items and dropdowns.
https://edifice-community.atlassian.net/browse/WB-2195
- [ ] Icons

Fix/wb 2195: Toolbar a11y navigation between items and dropdowns 

---

packages/editor/src/components/Renderer/LinkerRenderer.tsx

Tickets [WB-2507](https://edifice-community.atlassian.net/browse/WB-2507) et [WB-2523](https://edifice-community.atlassian.net/browse/WB-2523)
Le renderer du linker utilise un badge, mais en laissant son contenu éditable en mode édition. Cette PR 
+ rend le contenu non-éditable dans tous les cas,
+ Ajout d'une marge horizontale autour du badge, afin de faciliter le placement du curseur à la souris.
- [ ] Icons
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
[WB-2507]: https://edifice-community.atlassian.net/browse/WB-2507?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViL …

fix(editor): #WB-2507, #WB-2523 fix linker badge selection

---

packages/react/src/common/ShareModal/ShareModal.tsx
packages/react/src/common/ShareModal/hooks/useSearch.ts
packages/react/src/components/Combobox/Combobox.stories.tsx
packages/react/src/components/Combobox/Combobox.tsx
packages/react/src/components/Combobox/ComboboxTrigger.tsx

Fix share modal search start minimum length:
- because of performance for ADML the minimum length to start the search is 3
- for non ADML the search starts with 1 character
Added a prop `searchMinLength` to `ComboboxTrigger` to pass the value of the search minimum length.
- [ ] Icons

fix: #WB2-1357, fix share modal search start min length

---

packages/react/src/hooks/useDropdown/useDropdown.ts

Space event prevents user to insert Space during search, so we comment it to keep a trace.
- [ ] Icons

fix: #WB2-1334, fix space character in share modal search input

---

packages/react/src/common/ShareModal/hooks/useSearch.tsx
packages/react/src/components/Combobox/Combobox.stories.tsx
packages/react/src/components/Combobox/Combobox.tsx

Show sharebookmark icon in share modal search results.
Setting the icon prop to <Bookmark /> icon => I had to rename `useSearch.ts` file into `useSearch.tsx` as I am using a JSX element.
- [ ] Icons

fix: #WB2-1382, show sharebookmark icon in share modal search results

---

packages/react/src/components/Badge/Badge.stories.tsx
packages/react/src/components/Badge/Badge.tsx

Add variant options to badge's variant `Notification`. 
- level `info`
- color option `background` (default). The color from the level option will be applied on the background
- color option `text`. The color from the level option will be applied on the text color
- [ ] Icons

feat: Update badge with notification text color + notification level info

---

packages/react/src/hooks/useToast/useToast.tsx

Add id option and dismiss/remove function to toast.
When creating a toast, we can pass an `id` that will be used then to `dismiss` or `remove` the toast.
`dismiss` function will remove the toast after 1 second.
`remove` function will remove instantly the toast.
- [ ] Icons

Feat/wb2 850 Add id option and dismiss/remove function to toast

---

packages/react/src/core/useResourceSearch/useResourceSearch.ts
packages/react/src/multimedia/Linker/InternalLinker.tsx

Use the new `behaviour` service to display resources int the Linker.
See https://github.com/edificeio/edifice-ts-client/pull/32
- [ ] Icons

fix(core): WB-2615, use behaviour service to search among resources

---

packages/editor/src/components/Editor/Editor.tsx
packages/editor/src/hooks/useTipTapEditor.ts

Add a `focus` prop to Editor component to set focus on Editor.
- [ ] Icons

feat: #WB2-1588, add focus prop to Editor component

---

packages/editor/src/components/Editor/Editor.tsx
packages/editor/src/hooks/useImageModal.ts
packages/editor/src/hooks/useMediaLibraryModal.ts
packages/react/src/core/useUploadFiles/useUploadFiles.ts
packages/react/src/core/useWorkspaceFile/useWorkspaceFile.ts
packages/react/src/multimedia/MediaLibrary/MediaLibrary.tsx
packages/react/src/multimedia/MediaLibrary/MediaLibraryContext.tsx
packages/react/src/multimedia/MediaLibrary/innertabs/Upload.tsx
packages/react/src/multimedia/MediaLibrary/innertabs/Workspace.tsx
packages/react/src/multimedia/UploadFiles/UploadFiles.tsx
packages/react/src/multimedia/Workspace/Workspace.tsx

Fix issue with the import/select documents in multimedia library depending on the visibility.
When importing document we need to import it in the protected folder or public depending on the vibility we need.
When adding a document already existing in or workspace we need to transfer it to the correction place.
- [ ] Icons

fix: #WB-2679 bbm visibility

---

packages/editor/src/components/Editor/Editor.tsx
packages/editor/src/hooks/useTipTapEditor.ts

Ajout de onContentChange pour récupérer les changements du contenu de l'éditeur en direct 
Ticket : https://edifice-community.atlassian.net/browse/WB-2655
- [ ] Icons

fix: #WB-2566, add onContentChange to listen changement in editor

---

packages/react/src/multimedia/Workspace/Workspace.tsx

Show public documents in Workspace when public folder is selected on Media Library 'Workspace tab' load
- [ ] Icons

fix: #WB-2753, show public documents in Workspace when public folder is selected on Workspace tab load

---

packages/react/src/multimedia/AudioRecorder/useAudioRecorder.tsx
packages/react/src/multimedia/ImageEditor/effects/misc.ts

Using canvas to download image increase the file size. To keep the same size we need to apply decrease the blob quality before sending it to the server.
- [ ] Icons

fix: #WB-2799 keep image size

---

packages/react/src/components/Breadcrumb/Breadcrumb.tsx

Lors des tests d'accessibilité sur Blog, il est apparu que notre Breadcrumb affichait parfois des liens hypertexte sans `text node` ni `aria-label`s.
Le fix a consisté à ajouter les `aria-label`s manquants.
- [ ] Icons

fix(react): #WB-2793, add aria-labels to breadcrumb hyperlinks

---

packages/react/ui/src/components/Tabs/Tabs.tsx

The issue is due to focusing an input while in responsive display is triggering the windows resize event. And we are listening it and changing the focus which will close the virtual keyboard.
- [ ] Icons

fix(ui): #WB-2841 focus on input trigger windows resize + focus

---

packages/react/ui/src/multimedia/AudioRecorder/useAudioRecorder.tsx
public/infra/public/js/audioEncoder.js

The issue was due to firefox not allowing AudioContext to override the sample rate. To correct we just have to set by default the sample rate to 48000 which is the default value.
- [ ] Icons

fix(ui): #WB-2860 audio record on firefox

---

packages/react/ui/src/portal/Layout/Layout.tsx

In responsive mode when the keyboard is open the vertical scollbar is lock by the container div created by react-hot-toast. The fix is to decrease the z-index of the container.
- [ ] Icons

fix(ui): #WB-2828 responsive toaster block scrollbar

---

packages/react/ui/src/multimedia/VideoRecorder/VideoRecorder.tsx

The VideoRecorder should stop automatically when the max allowed record duration is reached.
Also, some code has been commented, simplified and improved :
- removed a not-so-useful useState(),
- better computation of the record time,
- [ ] Icons

fix(ui): #WB-2894, auto-stop recording when max duration is reached

---

packages/react/editor/src/components/Renderer/LinkerRenderer.tsx

[Ticket WB-2870](https://edifice-community.atlassian.net/browse/WB-2870)
Les liens internes historiques contiennent parfois du texte customisé, à afficher (si aucun autre texte n'est disponible).
- [ ] Icons

fix(editor): #WB-2870, Linker cards should always display content text

---

packages/react/ui/src/multimedia/Linker/InternalLinker.tsx

[Ticket WB-2858](https://edifice-community.atlassian.net/browse/WB-2858)
Le linker interne possède une barre de recherche, mais elle défile avec le contenu puis disparait lorsque il y a trop de contenus à afficher.
Cette PR la rend "sticky" => elle ne défile plus avec le contenu.
De plus, elle corrige un bug sur la sélection de contenus multiples, probablement issu d'une fusion de branche mal traitée.
- [ ] Icons

feat(ui): #WB-2858, sticky searchbar for the internal linker

---

packages/react/ui/src/components/Toolbar/Toolbar.stories.tsx
packages/react/ui/src/components/Toolbar/Toolbar.tsx

Fix toolbar a11y keyboard navigation with disabled elements:
If the first toolbar element was disabled then toolbar focus using Tab key was not working, so I set the toolbar focus on first non disabled element and set the navigation through non disabled elements.
- [ ] Icons
- [] Doc (PATCH)

fix: #WB2-1659, fix toolbar a11y keyboard navigation with disabled elements

---

packages/react/ui/src/components/TreeView/TreeItem.tsx
packages/react/ui/src/components/TreeView/hooks/useTreeItemEvents.tsx

- Hide rafter if treeview children array is empty
- Fold/unfold tree when clicking on item
- [ ] Icons

fix: #WB-2445, hide rafter if treeview children array is empty and fold/unfold tree when clicking on item

---

packages/client/src/ts/resources/behaviours/WorkspaceBehaviour.ts
packages/client/src/ts/workspace/Service.ts

Revert from the 150x150 thumbnail sizes used in Medialibrary.
- [ ] Icons

fix(ui): #WB-2862, use a default thumbnail size of 120x120 pixels

---

packages/react/ui/src/core/useUploadFiles/useUploadFiles.ts

Ajout d'une fonction de tri pour récupérer l'ordre de sélection depuis le navigateur.
Ticket : https://edifice-community.atlassian.net/browse/WB-3007
- [ ] Icons

fix: #WB-3007, add sort function to keep order select image

---

packages/react/ui/src/components/Dropzone/Dropzone.tsx
packages/react/ui/src/components/ImagePicker/ImagePicker.tsx
packages/react/ui/src/core/useUpload/useUpload.ts
packages/react/ui/src/core/useUploadFiles/useUploadFiles.ts
packages/react/ui/src/hooks/useDropzone/useDropzone.ts

Le bug provenait d'appels async couplés à une logique imbriquée dans ces appels => au final, on faisait trop d'uploads async.
Le problème était donc percu aléatoirement et amplifié par le nombre important de render React (ça ressortait d'autant plus avec le resize d'images).
Pour corriger : 
* refacto de la logique de déclenchement d'uploads, pour la séparer de l'upload effectif.
* appel à `setUploadStatus(idle)` pour bien discriminer les fichiers qui vont être uploadés dans la logique citée plus haut.
* application réelle d'un garde-fou à 5 uploads en simultanée (c'était buggé).
* Isolation du hook `useUploadFiles` : il ne dépend plus de l'implémentation de `useUpload` et n'a plus besoin d'utiliser `getOrGenerateBlobId`
* ajout de commentaires
* réduction des render React en permettant …

fix: #WB-3106, cleaner handling of files upload

---

packages/react/ui/src/common/ShareModal/ShareBookmark.tsx
packages/react/ui/src/common/ShareModal/ShareBookmarkLine.tsx
packages/react/ui/src/common/ShareModal/ShareModal.tsx
packages/react/ui/src/common/ShareModal/apps/ShareBlog.tsx
packages/react/ui/src/common/ShareModal/hooks/useSearch.tsx
packages/react/ui/src/common/ShareModal/hooks/useShare.ts
packages/react/ui/src/common/ShareModal/hooks/useShareBookmark.ts

https://edifice-community.atlassian.net/browse/WB2-1742
Add `shareOptions` props to make `ShareModal` self-sufficient. No more explorer call to share a resource.
`shareOptions` needs 3 informations:
- resourceId -> id of the resource aka `assetId`
- resourceCreatorId -> id of the user who created the resource
- resourceRights -> normalized rights `rights[]`
```
// e.g
const shareOptions = {
resourceCreatorId: data?.owner.userId,
resourceId: data?._id,
resourceRights: data?.rights,
};
```
Only "ShareBlog" component gets its resource from explorer (because the application uses explorer and this component is used in the explorer application)
- [ ] Icons

feat(ui): #WB2-1742, add shareOptions to make ShareModal compatible with any apps

---

packages/react/ui/src/components/Dropzone/Dropzone.tsx
packages/react/ui/src/components/Dropzone/DropzoneContext.tsx
packages/react/ui/src/core/useUploadFiles/useUploadFiles.ts
packages/react/ui/src/hooks/useDropzone/useDropzone.ts
packages/react/ui/src/hooks/useImageResizer/useImageResizer.ts

> [Ticket WB-2036](https://edifice-community.atlassian.net/browse/WB-2036)
Lors du resize d'image : 
- par défaut, conserve le format de l'image source si c'est _png_ ou _gif_, sinon passe en _jpeg_
- met à jour la liste des fichiers importés pour voir le type mime et le poids de l'image APRES resize
- [ ] Icons

feat(ui): #WB-2036, compress to a valid format when resizing an image

---

packages/react/ui/src/multimedia/AudioRecorder/AudioRecorder.tsx
packages/react/ui/src/multimedia/AudioRecorder/useAudioRecorder.tsx

Roll back from MediaRecorder and use audio preprocessor for safari better compatibility with MP3 audio recorder.
- [ ] Icons

fix: #WB-3014 rollback audio with preprocesseur for safari compatibility

---

packages/bootstrap/scss/components/tiptap/_iframe.scss
packages/react/ui/src/multimedia/MediaLibrary/innertabs/Iframe.tsx

WB-3148 issue was with tiptap not supporting `p` element in is custom node so we remplace them by a div
WB-3159 issue was with the position absolute in the embeded code one fix was introduce with the https://edifice-community.atlassian.net/browse/WB-3100 but it introduce some regression for other iframe. I replace the padding-bottom solution by a min-height.
- [ ] Icons

fix: #WB-3148 #WB-3159 embed code with p element + absolute position

---

packages/react/ui/src/common/ShareModal/ShareBookmarkLine.tsx

Ajout d'une nouvelle icône groupe dans la modal de partage : 
https://www.figma.com/design/A8noABDGvUFP8F3dGqG735/Library_Web?node-id=757-10225&t=vhu1aALrCQ2GowMJ-1
Ticket : https://edifice-community.atlassian.net/browse/WB2-1294
- [ ] Icons

fix: #WB2-1294, fix group icon in share modal

---

packages/react/ui/src/components/Tree/SortableTree.tsx
packages/react/ui/src/components/Tree/Tree.tsx
packages/react/ui/src/components/Tree/stories/SortableTree.stories.tsx
packages/react/ui/src/components/Tree/types.ts

We provide full node information to the renderNode function in Tree and SortableTree components.
We also provide the information of if the node is a child, useful for some cases (for example for displaying the "+" button only for parent node)
- [ ] Icons

feat: #WB2-1868, pass full node to Tree renderNode function

---

packages/tiptap/extensions/extension-attachment/src/Attachment.ts

Hotfix for links parsing for tiptap Attachment extension.
- [ ] Icons

fix: #WB2-2156, fix Attachment links parsing

---

packages/tiptap/extensions/extension-attachment/src/AttachmentTransformer.ts
packages/tiptap/extensions/extension-attachment/src/index.ts

Cette PR ajoute une extension attachment en mode inline pour le back tiptap-transformer
- [ ] Icons

fix: #WB2-2156, allow inline attachment

---

packages/react/src/components/List/List.mdx
packages/react/src/components/List/List.stories.tsx
packages/react/src/components/List/List.tsx

Add isCheckable option on List component to be able to have the global check without toolbar.
- [ ] Icons

feat: #WB-3735 add isCheckable props in List component

---

packages/react/src/modules/editor/components/Renderer/AttachmentRenderer.tsx

Fix page navigation Attachment update.
Attachment link state was not updated when prop changed in AttachmentRenderer so the attachment was not updated in the page.
- [ ] Icons

fix: #WB2-2243, fix page navigation Attachment update

---

packages/extensions/src/iframe/iframe.ts
packages/extensions/src/iframe/transformers/index.ts
packages/extensions/src/iframe/transformers/interface.ts
packages/extensions/src/iframe/transformers/pad-transformer.ts

Ce fix permet de transformer les URL de pad dans l extension iframe. Ainsi lorsqu'une URL de pad est détecté on redirige l'appel vers une URL embed de l'ent. Cette URL embed va crée une session etherpad puis va rediriger vers le pad.
On évite ainsi les soucis "d'accès non autorisé" au pad.
- [ ] Icons

fix: #wb2-2138, transform pad url in iframe

---

packages/react/src/hooks/useCheckable/useCheckable.ts

Update the useCheckable hook to ensure that selectedItems are updated when the data changes.
Fix : The issue fixed occurred when a selected item was deleted from the data. The item remained in the state, and the global checkbox incorrectly indicated that it was still selected.
- [ ] Icons

fix(list):#WB-3957 ensure selectedItems is consistent with data

---

packages/client/src/ts/configure/Service.ts

For Public pages like for example Public Blogs, the user is not authenticated so we can't know the user theme preference. Before this fix, we picked the first theme element in the `overriding` array of the `theme-conf.js` file located in the assets of the platform's springboard. Besides we used the first skin of the `skins` array.
For the Saas platform, the first element in the overriding array is the `ONE` theme and the first skin is `Circus` but for Public Blogs we would like to show the `NEO` theme with the `default` skin. So I updated the getTheme function in the client configure Service to retrieve the NEO theme if the access is Public.
- [ ] Icons

fix(client): #WB2-2660, pick neo theme for public theme

---

packages/client/src/ts/workspace/interface.ts
packages/config/src/msw/mocks/workspace/data/sharedFolders.ts
packages/config/src/msw/mocks/workspace/workspace.ts
packages/react/src/hooks/useWorkspaceFolders/index.ts
packages/react/src/hooks/useWorkspaceFolders/useWorkspaceFolders.ts
packages/react/src/hooks/useWorkspaceFolders/useWorkspaceFoldersTree.ts
packages/react/src/modules/multimedia/WorkspaceFolders/WorkspaceFolders.tsx

Show folder without contribution rights to browse into it and create folder into children with contribution rights
- [ ] Icons

feat(WorkspaceFolders):WB-3971 show folder without contrib right to browse into it

---

packages/react/src/components/List/List.tsx
packages/react/src/components/Toolbar/Toolbar.stories.tsx
packages/react/src/components/Toolbar/Toolbar.tsx

Toolbar : masquer texte des boutons en responsive ([Ticket](https://edifice-community.atlassian.net/browse/WB-4004))
- [ ] Icons

feat(ConfirmModal):WB-4004 hide toolbar labels on mobile

---

packages/bootstrap/src/abstracts/_variables.scss
packages/bootstrap/src/components/_modal.scss

modal padding to 24px up to md, then 32px 
Ticket : https://edifice-community.atlassian.net/jira/software/c/projects/WB/boards/234?assignee=712020%3Aa351bfd8-8169-43e4-821c-48991f7e3d43&selectedIssue=WB-4005
- [ ] Icons

fix(react):#WB-4005 fix modal padding

---

packages/extensions/src/conversation-history/conversation-history.ts
packages/react/src/modules/editor/components/Renderer/ConversationHistoryRenderer.tsx

The conversation history container can have multiple blocks as children.
- [ ] Icons

fix(conversation-history): #WB-3438 conversation history have multiple block children

---

packages/react/src/hooks/useDate/useDate.ts

J'ai mis à jour le hook useDate du FF en ajoutant la fonction formatTimeAgo qui devra être utilisé sur plusieurs app selon les [specs](https://edifice-community.atlassian.net/wiki/spaces/ODE/pages/2954428501/MB+docs+-+Format+des+dates+et+temps) ([Ticket Enabling](https://edifice-community.atlassian.net/browse/ENABLING-266))
Liée à la PR de conversation : https://github.com/edificeio/entcore/pull/705
- [ ] Icons

feat(react):#WB-3944 add formatTimeAgo to useDate hook

---

packages/react/src/components/Tooltip/Tooltip.tsx

applique le z-index du toomtip sur le tooltip et non sur la cible
- [ ] Icons

fix(conversation): #COCO-4210 fix Tooltip z-index

---

packages/bootstrap/src/components/_dropzone.scss
packages/react/src/hooks/useDropzone/useDropzone.ts
packages/react/src/hooks/useUploadFiles/useUploadFiles.ts

Lors de l'ajout PJ dans l'editeur,
https://edifice-community.atlassian.net/browse/COCO-4207
-  supprimer le fichier et le remettre ne fonctionnait pas 
Lorsqu'il n'y a pas d'espace disponible
- deux toast d'erreurs sont affiché au lieu d'un seul (car la requete est retenté avec l'image d'origine => ne plus avoir ce callback)
- upload la même image si il y a eu une erreur 
- [ ] Icons

fix(react,bootstrap):COCO-4207 editor-re-add-media-after-deletion

---

packages/react/src/modules/multimedia/VideoRecorder/VideoRecorder.tsx
packages/react/src/modules/multimedia/VideoRecorder/VideoRecorderToolbar.tsx
packages/react/src/modules/multimedia/VideoRecorder/useCameras.ts

* Refactor VideoRecorder code => broke it into a hook + a dedicated toolbar component
* Fix a bug : on devices with many cameras, the camera selector was not showing up if the device was asking for user user consent (a promise was resolved, but without updating the UI)
* Optimize rendering
https://edifice-community.atlassian.net/browse/COCO-4479
- [ ] Icons

fix(multimedia): COCO-4479, allow user to select a camera after giving his consent to use them

---

package.json
packages/client/src/ts/data/WebBroker.ts
packages/client/src/ts/notify/Framework.ts
packages/client/src/ts/notify/Observable.ts
packages/client/src/ts/notify/Subject.spec.ts
packages/client/src/ts/notify/Subject.ts
packages/client/src/ts/notify/interfaces.ts
packages/client/tsconfig.json
packages/react/src/hooks/useHttpErrorToast/useHttpErrorToast.ts
packages/react/src/modules/multimedia/MediaLibrary/MediaLibrary.tsx

Un problème survient lorsqu’un éditeur riche (par exemple, dans la messagerie) est ouvert dans un onglet, et qu’une erreur HTTP 401 se produit dans un second onglet du navigateur utilisant le framework.
En effet, MediaLibrary utilise un [hook générique afin de capter toutes les erreurs HTTP](https://github.com/edificeio/edifice-frontend-framework/blob/7db2a9ccf92b9a8364eec3cd322ee93ebf988635/packages/react/src/modules/multimedia/MediaLibrary/MediaLibrary.tsx#L223) pouvant se produire lors de l’utilisation du service “transport”.
Cette PR vise à : 
* abandonner l'usage des `BroadcastChannel` dans le package client, qui doit rester indépendant du DOM.
* ajouter une propriété `active` au hook `useHttpErrorToast` permettant d’activer ou non le toaster.
Please check the name of the package you …

feat(client): #COCO-4719, do not use BroadcastChannel in client
